### ISSUE TITLE
Unable to get it work

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/vim-compete-lamp#1]
Hi! I decided to try compete and vim-lamp.
I installed [vim-lamp](https://github.com/hrsh7th/vim-lamp), [vim-compete](git@github.com:hrsh7th/vim-compete.git) and this plugin.
Here is my configuration:
```vim
augroup vimrc
  autocmd!
augroup END

autocmd! vimrc User lamp#initialized call s:on_initialized()
function! s:on_initialized()
  call lamp#language#vim()
endfunction

"
" initialize buffers
"
autocmd! vimrc User lamp#text_document_did_open call s:on_text_document_did_open()
function! s:on_text_document_did_open() abort
  " completion
  setlocal omnifunc=lamp#complete

  " commands
  nnoremap <buffer> gf<CR>       :<C-u>LampDefinition edit<CR>
  nnoremap <buffer> gfs          :<C-u>LampDefinition split<CR>
  nnoremap <buffer> gfv          :<C-u>LampDefinition vsplit<CR>
  nnoremap <buffer> tgf<CR>      :<C-u>LampTypeDefinition edit<CR>
  nnoremap <buffer> tgfs         :<C-u>LampTypeDefinition split<CR>
  nnoremap <buffer> tgfv         :<C-u>LampTypeDefinition vsplit<CR>
  nnoremap <buffer> dgf<CR>      :<C-u>LampDeclaration edit<CR>
  nnoremap <buffer> dgfs         :<C-u>LampDeclaration split<CR>
  nnoremap <buffer> dgfv         :<C-u>LampDeclaration vsplit<CR>
  nnoremap <buffer> <Leader>i    :<C-u>LampHover<CR>
  nnoremap <buffer> <Leader>r    :<C-u>LampRename<CR>
  nnoremap <buffer> <Leader>g    :<C-u>LampReferences<CR>
  nnoremap <buffer> @            :<C-u>LampDocumentHighlight<CR>
  nnoremap <buffer> <Leader>@    :<C-u>LampDocumentHighlightClear<CR>
  nnoremap <buffer> <Leader>f    :<C-u>LampFormatting<CR>
  vnoremap <buffer> <Leader>f    :LampRangeFormatting<CR>
  nnoremap <buffer> <Leader><CR> :<C-u>LampCodeAction<CR>
  vnoremap <buffer> <Leader><CR> :LampCodeAction<CR>

  " mappings
  nmap <buffer> gf<CR>         <Plug>(lamp-definition)
  nmap <buffer> gfs            <Plug>(lamp-definition-split)
  nmap <buffer> gfv            <Plug>(lamp-definition-vsplit)
  nmap <buffer> tgf<CR>        <Plug>(lamp-type-definition)
  nmap <buffer> tgfs           <Plug>(lamp-type-definition-split)
  nmap <buffer> tgfv           <Plug>(lamp-type-definition-vsplit)
  nmap <buffer> dgf<CR>        <Plug>(lamp-declaration)
  nmap <buffer> dgfs           <Plug>(lamp-declaration-split)
  nmap <buffer> dgfv           <Plug>(lamp-declaration-vsplit)
  nmap <buffer> <Leader>i      <Plug>(lamp-hover)
  nmap <buffer> <Leader>r      <Plug>(lamp-rename)
  nmap <buffer> <Leader>g      <Plug>(lamp-references)
  nmap <buffer> <Leader>f      <Plug>(lamp-formatting)
  vmap <buffer> <Leader>f      <Plug>(lamp-range-formatting)
  nmap <buffer> @              <Plug>(lamp-document-highlight)
  nmap <buffer> <Esc>          <Plug>(lamp-document-highlight-clear)
  nmap <buffer> <Leader><CR>   <Plug>(lamp-code-action)
  vmap <buffer> <Leader><CR>   <Plug>(lamp-code-action)
endfunction
```
LSP initialized: 
![изображение](https://user-images.githubusercontent.com/22453358/77123817-df50e900-6a49-11ea-9128-f7f781685df0.png)
But compete not suggests LSP completion. Do I need manually add LSP completion source?

**Comment by hrsh7th** [comment]
You should provide more detailed information when creating an issue.

- Is buffer source works?
- Please provide `echomsg string(map(compete#source#find(), 'v:val.name'))` results.

BTW, I don't recommend those plugins (I often breaking changes to it)

**Comment by hrsh7th** [comment]
And I will remove all mapping feature from vim-lamp.

**Comment by Shatur** [comment]
Oh, I'm very sorry. I reinstalled this plugins today and LSP completion works now.

> Is buffer source works?

Yes, the buffer source worked.

**Comment by hrsh7th** [comment]
Sorry for taking your time.

Sometimes those plugins modified in my local environment.
And I often forget to push those changes.

So if you don't get the right result, please notify it for me.

**Comment by Shatur** [comment]
> BTW, I don't recommend those plugins (I often breaking changes to it)

Yes, I understand that this plugins are under active development. I just looking for alternatives for vim-lsp and asyncomplete. I I like your plugins, they work fast. For example, asyncomplete have performance issue [with file completion](https://github.com/prabirshrestha/asyncomplete-file.vim/issues/4) (compete just works with file completion as expected). I also used MUcomplete and it have performance issues with spell completion (yes, this is not implemented in compete).

**Comment by hrsh7th** [comment]
vim-lamp is works well now but vim-compete is not...

Anyway you seems understood your risk so I don't stop you.
